<?php
// Automatically Generated by TestLink Installer - Fri, 02 May 14 14:49:30 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'loren');
define('DB_PASS', 'loren');
define('DB_HOST', 'mysql' . ':' . '3306');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
